### ISSUE TITLE
Selective export of some spectra variables

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendMgf#14]
Some platforms like GNPS don't support additional exported fields. Thus, a variable specifying which `spectraVariables` to export might be helpful in the `export` method.

**Comment by jorainer** [comment]
The solution is to use the `selectSpectraVariables` before the export to restrict the `Spectra` object to only those spectra variables that should be exported:

```r
ps_ex <- selectSpectraVariables(sps, c("mz", "intensity", "rtime",
                                        "acquisitionNum", "precursorMz",
                                        "precursorCharge"))
export(sps_ex, backend = MsBackendMgf(), file = fl)
```

**Comment by Felipe-rdv** [comment]
Dear @jorainer,

Thanks for the help with this question.
However, I would like to know how to remove the variable "TITLE", because even if I haven't selected this variable it continues to be exported.
The presence of the TITLE variable in this way is causing a conflict in GNPS.

See this reproducible example:

library(Spectra)
library(MsBackendMgf)

fls <- dir(system.file("extdata", package = "MsBackendMgf"),
           full.names = TRUE, pattern = "mgf$")

sps <- Spectra(fls, source = MsBackendMgf())
sps$TITLE
sps$acquisitionNum

#selecting only c("mz", "intensity", "rtime", "precursorMz")
ps_ex <- selectSpectraVariables(sps, c("mz", "intensity", "rtime", "precursorMz"))
ps_ex$TITLE
ps_ex$mz

fl <- tempfile()
export(ps_ex, backend = MsBackendMgf(), file = fl)
readLines(fl)[1:12]

Ouput:

`
 [1] "BEGIN IONS"                                 "TITLE=msLevel NA; retentionTime ; scanNum "
 [3] "RTINSECONDS=1028"                           "PEPMASS=816.33826"                         
 [5] "102.0548 753.738"                           "103.00494 385.376"                         
 [7] "103.03531 315.441"                          "115.05001 413.206"                         
 [9] "115.08686 588.273"                          "120.08063 800.016"                         
[11] "124.10555 526.761"                          "124.20652 326.013"               
`

another question:
is it possible to export the variable CHARGE with symbol?
example: CHARGE=1+

thank you,

**Comment by lgatto** [comment]
I think the TITLE field is required for a valid mgf, so it might make sense to keep it. 

You can however remove that line with a perl one-liner. 

```
perl -pi.org -e 's/^TITLE.+//g' 100_consensus.mgf
```
will remove all lines that start with TITLE in the file `100_consensus.mgf` and back the previous version of that file as `100_consensus.mgf.org`. You could achieve the same thing with 
```
grep -v TITLE file.mgf > new_file.mgf
```

As for the charge, should be add this as an option to the backend exporter, @jorainer ?

**Comment by jorainer** [comment]
@Felipe-rdv, is it the presence of the TITLE in the output mgf or the information exported in the TITLE field that causes problems? The TITLE field is a supported field from MGF (see [definition](https://www.matrixscience.com/help/data_file_help.html)) and I would also not like to drop that field if not absolutely necessary.

Regarding the charge, what you could do as an intermediate fix is:

```r
sps$CHARGE <- precursorCharge(sps)
sps$CHARGE <- paste0(sps$CHARGE, ifelse(precursorCharge(sps) > 0, "+", "-"))
## Get rid of "NA"
sps$CHARGE[grep("NA", sps$CHARGE)] <- NA_character_

## Then you could also export this variable
ps_ex <- selectSpectraVariables(sps, c("mz", "intensity", "rtime", "precursorMz", "CHARGE"))
```

**Comment by jorainer** [comment]
In long term we need to support export of the charge in correct format (-> issue #16)

**Comment by Felipe-rdv** [comment]
Dear @lgatto,
thank you for the help and assistance with perl code. will certainly help make it work.

Dear @jorainer, thank you for the help and I will test you code and will let you know.

About the "TITLE" field:
This turned out to be an interesting case.
In this case I'm working to perform an output similar to MZMINE's output so I can submit it to GNPS "Feature-Based Molecular Networking".

Following their tutorial at:
https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mzmine2/

we can find several file formats of MGF files that they accept as "input". However, most of them don't seem to have the "TITLE" field. This could be the problem, because when there is this variable "unforeseen" it crashes.

See these examples:

MZMINE:
https://raw.githubusercontent.com/CCMS-UCSD/GNPSDocumentation/master/docs/tutorials/AG_tutorial_files/MZmine-GNPS_AG_test_GNPS.mgf

MSDIAL:
https://raw.githubusercontent.com/CCMS-UCSD/GNPSDocumentation/master/docs/tutorials/AG_tutorial_files/MS-DIAL-GNPS_AG_test_GNPS.mgf

Thank you guys for your kind help,

My best,

**Comment by jorainer** [comment]
Thanks @Felipe-rdv for the additional information. But then maybe we should have an option to disable export of the TITLE field. Maybe with an option `export(... , exportTitle = TRUE)`? @lgatto what do you think?

**Comment by lgatto** [comment]
> Maybe with an option `export(... , exportTitle = TRUE)`? 

Yes, fine by me.

**Comment by jorainer** [comment]
@Felipe-rdv , if you use the most recent `MsBackendMgf` package version (`BiocManager::install("RforMassSpectrometry/MsBackendMgf")` you'll have an extra parameter `exportTitle` and if you set that to `FALSE` the TITLE field will not be written.

**Comment by Felipe-rdv** [comment]
Dear @jorainer and @lgatto,
thanks for your attention and help.
everything worked perfectly,
my best regards,

**Comment by Felipe-rdv** [comment]
Dear @jorainer,

Unfortunately it is having problems exporting the CHARGE variable.
It is exporting 2 "charge" variables:
"CHARGE="
"CHARGE.1=2+"

Please see the reproducible example below:
```

library(Spectra)
library(MsBackendMgf)

fls <- dir(system.file("extdata", package = "MsBackendMgf"),
           full.names = TRUE, pattern = "mgf$")

sps <- Spectra(fls, source = MsBackendMgf())

sps$CHARGE <- precursorCharge(sps)
sps$CHARGE <- paste0(sps$CHARGE, ifelse(precursorCharge(sps) > 0, "+", "-"))
## Get rid of "NA"
sps$CHARGE[grep("NA", sps$CHARGE)] <- NA_character_

#selecting
ps_ex <- selectSpectraVariables(sps, c("mz", "intensity", "rtime", "precursorMz","CHARGE"))
ps_ex$CHARGE

fl <- tempfile()
export(ps_ex, backend = MsBackendMgf(), file = fl,exportTitle = FALSE)
readLines(fl)[1:12]
```


output:

```
 [1] "BEGIN IONS"        "RTINSECONDS=1028" 
 [3] "PEPMASS=816.33826" "CHARGE="          
 [5] "CHARGE.1=2+"       "102.0548 753.738" 
 [7] "103.00494 385.376" "103.03531 315.441"
 [9] "115.05001 413.206" "115.08686 588.273"
[11] "120.08063 800.016" "124.10555 526.761"
```

thank you,
